# TASK 1 ,2

In [4]:
#import all the required libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.keys import Keys

In [5]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [6]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://www.amazon.in/'
    #getting the driver
driver.get(URL)
    #promting the user to enter search item
Item=input("Enter The Item you want to search for:")
#passing the search item in search box 
Search = driver.find_element_by_xpath("//input[@id='twotabsearchtextbox']").send_keys(Item)
    #clicking the search button
search_btn = driver.find_element_by_xpath("//input[@id='nav-search-submit-button']").click()
Pagesurl= []
#maximising window as next button was not clicking when window size is small.
driver.maximize_window()
for i in range(3):
         #saves url of present page
        driver.current_url
        Pagesurl.append(driver.current_url)
        next_button = WebDriverWait(driver, 10).until(EC.visibility_of_element_located((By.PARTIAL_LINK_TEXT, "Next")))
        next_button.click()
        print(i+1,":page URL::",Pagesurl[i])

Enter The Item you want to search for:guitars
1 :page URL:: https://www.amazon.in/s?k=guitars&ref=nb_sb_noss
2 :page URL:: https://www.amazon.in/s?k=guitars&page=2&qid=1619445281&ref=sr_pg_1
3 :page URL:: https://www.amazon.in/s?k=guitars&page=3&qid=1619445289&ref=sr_pg_2

In [7]:
#creating empty listsfor storing urls, Expected delivery, availability, Exchanges
links = []
Expected_Delivery = []
availability = []
ReturnORexchange = []
RatingsNumber = []
Ratings = []
brand = []
product = []
price = []
for i in range(len(Pagesurl)):
    try:
        driver.get(Pagesurl[i])
        print("page no:",i+1)
        products_url = driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']")
        print("page no:",i+1,"has:",len(products_url),"products")# finding urls of all items in the present page
        for i in range(len(products_url)):
            links.append(products_url[i].get_attribute("href"))# traversing through each and every products link
    except NoSuchElementException as e:
        continue

page no: 1
page no: 1 has: 61 products
page no: 2
page no: 2 has: 51 products
page no: 3
page no: 3 has: 50 products

In [8]:
print(len(links))

162

In [11]:
for i in range(len(links)): 
    driver.get(links[i])#getting driver for urls of items stored in links.
    #as brand name and cost are must presentfor every item, not placed them intry block
    productname = driver.find_element_by_xpath("//*[@id='productTitle']")
    product.append(productname.text)# storing the text format of extracted data into list named Bname_1.#In the Bname list, we get titles of each item,if we notice the brand name comes first followed by description of item.
       # Bname[j] = Bname[j].split(" ", 1)# splitting each list values into 2 based on 1 st occuring space.
        #brand.append(Bname[j][0])# Appending the 1 st element of each row to brand
        #product.append(Bname[j][1])## Appending 2 nd element of each row to product.
    try:
        brandname=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[35]/div/table/tbody/tr[1]/td[2]/span')
        brand.append(brandname.text)
    except NoSuchElementException:
        brand.append('---')
    try:
        Cost = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[9]/div[1]/div/table/tbody/tr[2]/td[2]/span[1]')
        price.append(Cost.text)
    except NoSuchElementException as e:
        price.append("---")
    try:
        NoOfRatings = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[5]/div/span[3]/a/span")
        RatingsNumber.append(NoOfRatings.text)
    except NoSuchElementException as e:
        RatingsNumber.append("---")
    try:
        ratings = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[5]/div/span[1]/span/span[1]/a/i[1]/span")
        Ratings.append(ratings.text)
    except NoSuchElementException as e:
        Ratings.append("---")
    try:
        Delivery = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[11]/div/div/b")
        Expected_Delivery.append(Delivery.text)
    except NoSuchElementException as e:
        Expected_Delivery.append("NO DATA")
    try:
        Exchange = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[19]/div[2]/div/div/div/div[2]/span/div[2]/a")
        ReturnORexchange.append(Exchange.text)
    except NoSuchElementException as e:
        ReturnORexchange.append("NO DATA")
    try:
        Availability = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[21]/div[1]/span")
        availability.append(Availability.text)
    except NoSuchElementException as e:
        availability.append("NO DATA")

print("BrandName",len(brand))
print("product name:",len(product))
print("Rating",len(Ratings))
print("ofRatings",len(RatingsNumber))
print("Price",len(price))
print("Return/Excahnge",len(ReturnORexchange))
print("Expected Delivery",len(Expected_Delivery))
print("Availability",len(availability))
print("Product URL",len(links))

BrandName 163
product name: 163
Rating 163
ofRatings 163
Price 163
Return/Excahnge 163
Expected Delivery 163
Availability 163
Product URL 162

In [23]:
links[161]

'https://www.amazon.in/Belear-I-280-WBR-Couturier-Cutaway-Acoustic/dp/B092M7WCPK/ref=sr_1_146?dchild=1&keywords=guitars&qid=1619445317&sr=8-146'

In [40]:
Amazon_df = pd.DataFrame()

In [41]:
Amazon_df

Empty DataFrame
Columns: []
Index: []

In [42]:
AmazonProds_df['Brand Name']=brand[:-1]
AmazonProds_df['product name']=product[:-1]
AmazonProds_df['Rating']=Ratings[:-1]
AmazonProds_df['No.ofRatings']=RatingsNumber[:-1]
AmazonProds_df['Price']=price[:-1]
AmazonProds_df['Return/Excahnge']=ReturnORexchange[:-1]
AmazonProds_df['Expected Delivery']=Expected_Delivery[:-1]
AmazonProds_df['Availability']=availability[:-1]
AmazonProds_df['Product URL']=links

In [44]:
AmazonProds_df.to_csv('amazonproducts.csv')

# TASK 3

In [45]:
#creating driver object

driver=webdriver.Chrome(r"C:/chromedriver.exe")
#getting driver
driver.get("https://images.google.com")

In [46]:
#search box
enter=driver.find_element_by_xpath("//input[@class='gLFyf gsfi']")

In [47]:
#sending search item to the search box
enter.send_keys('fruits')
#pressing enter
enter.send_keys(Keys.ENTER)
#saving the screen shots of the fruits images to a folder(D:\Images) in my d drive.with the namefruits appended with the count of image.
for i in range(1, 102):
    try:
        driver.find_element_by_xpath('//*[@id="islrg"]/div[1]/div['+str(i)+']/a[1]/div[1]/img').screenshot('D:\Images\fruits ('+str(i)+').png')
    except:
        pass

In [48]:
#THE SEARCH BOX id, class changes after first search,so getting the details of the search box
entering=driver.find_element_by_xpath("//input[@id='REsRA']")

#clearing the contents of search box
entering.clear()

In [49]:
#sending our search item-car to the search box
entering.send_keys('cars')
#pressing enter
entering.send_keys(Keys.ENTER)
#saving screen shot of each item in the local directory with path D:\Imageswith the name cars appended with the count of image.
for i in range(1, 102):
    try:
        driver.find_element_by_xpath('//*[@id="islrg"]/div[1]/div['+str(i)+']/a[1]/div[1]/img').screenshot('D:\Images\cars ('+str(i)+').png')
    except:
        pass

In [50]:
#THE SEARCH BOX id, class changes after first search,so getting the details of the search box
entering=driver.find_element_by_xpath("//input[@id='REsRA']")

#clearing the contents of search box
entering.clear()

In [51]:
#sending our search item-car to the search box
entering.send_keys('Machine Learning')
#pressing enter
entering.send_keys(Keys.ENTER)
#saving screen shot of each item in the local directory with path D:\Images with the name machine learning appended with the count of image.
for i in range(1, 102):
    try:
        driver.find_element_by_xpath('//*[@id="islrg"]/div[1]/div['+str(i)+']/a[1]/div[1]/img').screenshot('D:\Images\Machine Learning ('+str(i)+').png')
    except:
        pass

In [52]:
#closing the driver
driver.close()

# TASK 5

In [53]:
from selenium.webdriver import ActionChains

In [54]:
#creating driver object

driver=webdriver.Chrome(r"C:/chromedriver.exe")
#getting driver
driver.get("https://www.google.com/maps")

In [55]:
#input box
city=driver.find_element_by_xpath("//input[@id='searchboxinput']")
#promting the user to enter search item
searchItem=input("Enter The city to search for:")
#passing the search item to page
city.send_keys(searchItem)

Enter The city to search for:Hyderabad

In [56]:
#clicking search button through code.
search_btn=driver.find_element_by_xpath("//button[@id='searchbox-searchbutton']")
search_btn.click()

In [57]:
#creating object for ActionChains class
actionChains = ActionChains(driver)

In [59]:
details=driver.find_element_by_xpath("//div[@id='hovercard']")

In [60]:
#performing right click through code,because only after right click the values of latitude and longitude gets populated.
actionChains.context_click(details).perform()

In [61]:
#getting details of dialog box after right click
Latlong=driver.find_element_by_xpath("//div[@id='hovercard']")

In [62]:
#saving the text
Latlong=Latlong.text.replace("\n",",")

In [65]:
Latlong=Latlong.split(",")

In [67]:
print("Latitude and logitude :",Latlong[0]+Latlong[1])

Latitude and logitude : 17.85321 78.12785

In [68]:
#closing the page
driver.close()

# TASK 6

In [69]:
#creating driver object

driver=webdriver.Chrome(r"C:/chromedriver.exe")
driver.get("https://trak.in/")

In [70]:
driver.maximize_window()

In [71]:
fundDeal=driver.find_element_by_xpath("//li[@id='menu-item-51510']")

In [72]:
#clicking fundeal button
fundDeal.click()

In [73]:
#creating empty list for each column of a month,
#As there are 9 columns for every month,creating 9 empty columns for each month
July_1=[]
July_2=[]
July_3=[]
July_4=[]
July_5=[]
July_6=[]
July_7=[]
July_8=[]
July_9=[]
Aug_1=[]
Aug_2=[]
Aug_3=[]
Aug_4=[]
Aug_5=[]
Aug_6=[]
Aug_7=[]
Aug_8=[]
Aug_9=[]
sep_1=[]
sep_2=[]
sep_3=[]
sep_4=[]
sep_5=[]
sep_6=[]
sep_7=[]
sep_8=[]
sep_9=[]

In [75]:
#recursively storing every element of the column to the above lists.
for i in range(10):
    #extracting all the  column of july 2020 one by oneand appending to the list
    July_1.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[1]').text)
    July_2.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[2]').text)
    July_3.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[3]').text)
    July_4.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[4]').text)
    July_5.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[5]').text)
    July_6.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[6]').text)
    July_7.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[7]').text)
    July_8.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[8]').text)
    July_9.append(driver.find_element_by_xpath('//*[@id="tablepress-48"]/tbody/tr['+str(i+1)+']//td[9]').text)
#extracting all the  column of August 2020 one by oneand appending to the list
    Aug_1.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[1]').text)
    Aug_2.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[2]').text)
    Aug_3.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[3]').text)
    Aug_4.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[4]').text)
    Aug_5.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[5]').text)
    Aug_6.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[6]').text)
    Aug_7.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[7]').text)
    Aug_8.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[8]').text)
    Aug_9.append(driver.find_element_by_xpath('//*[@id="tablepress-49"]/tbody/tr['+str(i+1)+']//td[9]').text)
#extracting all the  column of september 2020 one by oneand appending to the list
    sep_1.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[1]').text)
    sep_2.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[2]').text)
    sep_3.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[3]').text)
    sep_4.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[4]').text)
    sep_5.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[5]').text)
    sep_6.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[6]').text)
    sep_7.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[7]').text)
    sep_8.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[8]').text)
    sep_9.append(driver.find_element_by_xpath('//*[@id="tablepress-50"]/tbody/tr['+str(i+1)+']//td[9]').text)

In [76]:
#appending the lists to the data frame.
july_df=pd.DataFrame({ 'Sr.No':July_1,
                      'Date':July_2,
                      'company name':July_3,
                      'Industry/Vertical':July_4,
                      'Sub-vertical':July_5,
                      'City/Location':July_6,
                      'Investor Name':July_7,
                      'Investment_type':July_8,
                      'Amount in USD':July_9
                      
    
})

In [77]:
#appending the lists to the data frame.
Aug_df=pd.DataFrame({ 'Sr.No':Aug_1,
                      'Date':Aug_2,
                      'company name':Aug_3,
                      'Industry/Vertical':Aug_4,
                      'Sub-vertical':Aug_5,
                      'City/Location':Aug_6,
                      'Investor Name':Aug_7,
                      'Investment_type':Aug_8,
                      'Amount in USD':Aug_9
                      
    
})

In [78]:
#appending the lists to the data frame.
sep_df=pd.DataFrame({ 'Sr.No':sep_1,
                      'Date':sep_2,
                      'company name':sep_3,
                      'Industry/Vertical':sep_4,
                      'Sub-vertical':sep_5,
                      'City/Location':sep_6,
                      'Investor Name':sep_7,
                      'Investment_type':sep_8,
                      'Amount in USD':sep_9
                      
    
})

In [79]:
#displaying the data frame.
july_df

,Sr.No,Date,company name,Industry/Vertical,Sub-vertical,City/Location,Investor Name,Investment_type,Amount in USD
0,1,15/07/2020,Flipkart,E-commerce,E-commerce,Bangalore,Walmart Inc,M&A,"1,200,000,000"
1,2,16/07/2020,Vedantu,EduTech,Online Tutoring,Bangalore,Coatue Management,Series D,"100,000,000"
2,3,16/07/2020,Crio,EduTech,Learning Platform for Developers,Bangalore,021 Capital,pre-Series A,"934,160"
3,4,14/07/2020,goDutch,FinTech,Group Payments,Mumbai,"Matrix India,Y Combinator, Global Founders Cap...",Seed,"1,700,000"
4,5,13/07/2020,Mystifly,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Singapore and Bangalore,Recruit Co. Ltd.,pre-Series B,"3,300,000"
5,6,09/07/2020,JetSynthesys,Gaming and Entertainment,Gaming and Entertainment,Pune,Adar Poonawalla and Kris Gopalakrishnan.,Venture-Series Unknown,"400,000"
6,7,10/07/2020,gigIndia,Marketplace,"Crowd Sourcing, Freelance",Pune,Incubate Fund India and Beyond Next Ventures,pre-Series A,"974,200"
7,8,15/07/2020,PumPumPum,Automotive Rental,Used Car-leasing platform,Gurgaon,Early Adapters Syndicate,Seed,"292,800"
8,9,14/07/2020,FLYX,OTT Player,Streaming Social Network,New York and Delhi,"Raj Mishra, founder of AIT Global Inc",pre-Seed,"200,000"
9,10,13/07/2020,Open Appliances Pvt. Ltd.,Information Technology,Internet-of-Things Security Solutions,Bangalore,Unicorn India Ventures,Venture-Series Unknown,"500,000"

In [80]:
Aug_df

,Sr.No,Date,company name,Industry/Vertical,Sub-vertical,City/Location,Investor Name,Investment_type,Amount in USD
0,1,15/08/2020,Practo,HealthTech,Health care and Wellness,Bangalore,A1A Company,Series F,"32,000,000"
1,2,13/08/2020,Medlife,E-commerce,Online Pharmacy,Bangalore,Prasid Uno Family Trust and SC Credit Fund,,"23,000,000"
2,3,13/08/2020,HungerBox,FoodTech,Online Food Delivery Service,Bangalore,"One97, Sabre Partners Trust, Pratithi Investme...",Series D1,"1,560,000"
3,4,04/08/2020,Dunzo,Hyper-local Logistics,Online Delivery Services,Bangalore,Existing Backers,In Progress,"30,000,000"
4,5,11/08/2020,Terra.do,EduTech,"Online Climate School, E-learning","Stanford, California,","Stanford Angels and Entrepreneurs (India), BEE...",Seed,"1,400,000"
5,6,12/08/2020,Classplus,EduTech,"E-learning, Online Tutoring",Noida,Falcon Edge,In Progress,"upto 15,000,000"
6,7,14/08/2020,Niyo,FinTech,Financial Services,Bangalore,Niyo Solutions Inc.,,"6,000,000"
7,8,10/08/2020,ZestMoney,FinTech,Financial Services,Bangalore,Primrose Hills Ventures,,"10,670,000"
8,9,07/08/2020,FreshToHome,E-commerce,Food Delivery,Bangalore,Ascent Capital,Venture,"16,200,000"
9,10,13/08/2020,Eduvanz,FinTech,Financial Services,Mumbai,"Sequoia India, Unitus",Series A,"5,000,000"

In [81]:
sep_df

,Sr.No,Date,company name,Industry/Vertical,Sub-vertical,City/Location,Investor Name,Investment_type,Amount in USD
0,1,08/09/2020,Byju’s,EduTech,Online Tutoring,Bangalore,"Silver Lake, Tiger Global, General Atlantic an...",Private Equity,"500,000,000"
1,2,12/09/2020,mCaffeine,Personal Care,Skincare & Haircare,Mumbai,"Amicus Capital Private Equity I LLP, Amicus Ca...",Series B,"3,000,000"
2,3,09/09/2020,Qshala,EduTech,Online Curiosity Platform for Kids,Bangalore,Rainmatter Capital,Angel,"370,000"
3,4,02/09/2020,Winzo,Online Gaming,Online Gaming,New Delhi,"Kalaari Capital Partners, IndigoEdge Managemen...",Series B,"15,500,000"
4,5,09/09/2020,Hippo Video,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Newark, Delaware, United States of Amercia","Alpha Wave Incubation, Exfinity Venture Partne...",Series A,"4,500,000"
5,6,07/09/2020,Melorra,E-commerce,Online Jewelry Store,Bangalore,"Shadow Holdings, Lightbox.",Debt Financing,"upto 8,900,000"
6,7,07/09/2020,1mg,E-commerce,Online Pharmacy,Gurgaon,"Gaja Capital, Tata Capital, Partners Group",In Progress,"100,000,000"
7,8,31/08/2020,mfine,HealthTech,On-Demand Healthcare Services,Bangalore,Caretech Pte Inc,Series B,"5,400,000"
8,9,31/08/2020,Apna,Human Resources,Recruitment Platform,Bangalore,Lightspeed India and Sequoia Capital India,Series A,"8,000,000"
9,10,03/09/2020,Railofy,Transportation,WL & RAC protection platform,Mumbai,Chiratae Ventures,Seed,"950,000"

In [82]:
#closing the window
driver.close()

# TASK 7

In [128]:
#creating driver object

driver=webdriver.Chrome(r"C:/chromedriver.exe")
driver.get("https://www.digit.in/#search")

In [129]:
driver.maximize_window()

In [130]:
Search=driver.find_element_by_xpath("//input[@id='globalPageSearchText']")

In [131]:
searchItem=input("Enter Search item:")

Enter Search item:gaming laptop

In [132]:
#passing the search item to page
Search.send_keys(searchItem)

In [133]:
#pressing enter key
Search.send_keys(Keys.ENTER)

In [154]:
laptops=driver.find_elements_by_xpath("//div[@class='searchPage']")

In [152]:
#extracting urls of each product.
product_1=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[3]/a").get_attribute("href")
product_2=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[4]/a").get_attribute("href")
product_3=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[5]/a").get_attribute("href")
product_4=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[6]/a").get_attribute("href")
product_5=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[7]/a").get_attribute("href")
product_6=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[8]/a").get_attribute("href")
product_7=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[9]/a").get_attribute("href")
product_8=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[10]/a").get_attribute("href")
product_9=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[11]/a").get_attribute("href")
product_10=driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[12]/a").get_attribute("href")

In [183]:
#placing all the urls of gaming laptops into alist.
Allproducts_urls=[product_1,product_2,product_3,product_4,product_5,product_6,product_7,product_8,product_9,product_10]

In [199]:
#creating empty lists to store data about laptops.
laptop_name=[]
price=[]
keySpecs=[]
headerbar=[]

In [200]:
for i in range(len(Allproducts_urls)):
    #going to page of each product
    driver.get(Allproducts_urls[i])
    laptop_name.append(driver.find_element_by_xpath('/html/body/div[7]/div/div/div[1]/h1').text)
    price.append(driver.find_element_by_xpath('/html/body/div[7]/div/div/div[6]/div/div[2]/div[4]/div[1]/b').text)
    keySpecs.append(driver.find_element_by_xpath('/html/body/div[7]/div/div/div[6]/div/div[2]/div[3]/div').text)
    headerbar.append(driver.find_element_by_xpath('/html/body/div[7]/div/div/div[6]/div/div[2]/div[1]').text)

In [202]:
#displaying information product wise
for i in range(10):
    print("PRODUCT NUMBER:",i+1)
    print("\nlaptop name:",laptop_name[i])
    print("\nlaptop price:",price[i])
    print("\nlaptop specs:\n",keySpecs[i]) 
    print("\nother info:\n",headerbar[i])
    print("****************************************************************************************************************")

PRODUCT NUMBER: 1

laptop name: ASUS GX501 Zephyrus Gaming Laptop

laptop price: 409,999

laptop specs:
 OS
Windows 10 Pro
Display
15.6" (1920 X 1080)
Processor
Intel® Core™ I7 7700HQ | NA
Memory
1 TB SSD/24GB SDRAM

other info:
 Market Status : LAUNCHED
Release Date : 15-Jan-2018
Official Website : Asus
****************************************************************************************************************
PRODUCT NUMBER: 2

laptop name: Asus G750JX-CV069P

laptop price: 149,999

laptop specs:
 OS
NA
Display
NA
Processor
NA

other info:
 Market Status : LAUNCHED
Release Date : 14-Oct-2014
Official Website : Asus
****************************************************************************************************************
PRODUCT NUMBER: 3

laptop name: Asus TUF Gaming A17

laptop price: 84,552

laptop specs:
 OS
Windows 10 Pro
Display
17.3 MP | NA
Processor
NA
Memory
NA Null/NullGB DDR4

other info:
 Market Status : LAUNCHED
Release Date : 02-Jun-2020
Official Website : Asus
****************************************************************************************************************
PRODUCT NUMBER: 4

laptop name: ASUS TUF Gaming A15 Ryzen 9 4900H

laptop price: 96,990

laptop specs:
 OS
Pre-Loaded Windows 10 Home
Display
15.6 Inch" (1920 X 1080)
Processor
AMD Ryzen 9 4900H | 3.3 GHz
Memory
1 TB HDD/16GBGB DDR4

other info:
 Market Status : LAUNCHED
Release Date : 14-Dec-2020
Official Website : Asus
****************************************************************************************************************
PRODUCT NUMBER: 5

laptop name: Alienware M14x

laptop price: 86,200

laptop specs:
 OS
NA
Display
NA
Processor
NA

other info:
 Market Status : LAUNCHED
Release Date : 08-Nov-2011
Official Website : Dell
****************************************************************************************************************
PRODUCT NUMBER: 6

laptop name: HP Omen Ryzen 5 4600H

laptop price: 85,990

laptop specs:
 OS
Windows 10 Home
Display
15.6 Inch" (1920 X 1080)
Processor
Ryzen 5 Hexa Core | 3 GHz
Memory
512 GB SSD/NA DDR4

other info:
 Market Status : LAUNCHED
Release Date : 14-Dec-2020
Official Website : HP
****************************************************************************************************************
PRODUCT NUMBER: 7

laptop name: MSI Gaming GL63 9RDS-853IN

laptop price: 89,000

laptop specs:
 OS
Windows 10 Home
Display
15.6" (1920 X 1080)
Processor
8th Gen Core I7-8750H | NA
Memory
1 TB SATA/16GB DDR4

other info:
 Market Status : LAUNCHED
Release Date : 15-Jul-2019
Official Website : MSI
****************************************************************************************************************
PRODUCT NUMBER: 8

laptop name: Acer Predator Triton 700

laptop price: 299,999

laptop specs:
 OS
Windows 10 Home
Display
15.6" (1920 X 1080)
Processor
Intel Core I7-7700HQ | NA

other info:
 Market Status : LAUNCHED
Release Date : 24-Oct-2017
Official Website : Acer
****************************************************************************************************************
PRODUCT NUMBER: 9

laptop name: ASUS TUF Gaming FX505DD-AL185T

laptop price: 57,990

laptop specs:
 OS
Windows 10
Display
15.6" (1920 X 1080)
Processor
NA
Memory
1 TB NA/8 GBGB DDR4

other info:
 Market Status : LAUNCHED
Release Date : 19-Jun-2020
Official Website : Asus
****************************************************************************************************************
PRODUCT NUMBER: 10

laptop name: HP Envy 15-K006tx

laptop price: 80,510

laptop specs:
 OS
NA
Display
NA
Processor
NA

other info:
 Market Status : LAUNCHED
Release Date : 14-Oct-2014
Official Website : HP
****************************************************************************************************************

In [203]:
#closing the page
driver.close()