In [125]:
#import all the required libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.common.exceptions import  NoSuchElementException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# TASK 1

In [126]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos#Top_videos'
    #getting the driver
driver.get(URL)

In [127]:
#creating empty lists for saving the data.
ranks=[]
Name=[]
Artist=[]
uploaddate=[]
views=[]

In [128]:
#Adding values to the lists.
for i in range(30):

    ranks.append(driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i+1)+']/td[1]').text)
    Name.append(driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i+1)+']/td[2]').text)
    Artist.append(driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i+1)+']/td[3]').text)
    views.append(driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i+1)+']/td[4]').text)
    uploaddate.append(driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i+1)+']/td[5]').text)

In [129]:
#saving lists as columns  to data frame.
youtubeviews_df=pd.DataFrame({'RANK':ranks,
                                      'Video Name':Name,
                                      'Uploader':Artist,
                                      'Views':views,
                                      'Upload Date':uploaddate
                                     })

In [130]:
#final data frame.
youtubeviews_df

,RANK,Video Name,Uploader,Views,Upload Date
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,8.44,"June 17, 2016"
1,2.,"""Despacito""[24]",Luis Fonsi,7.32,"January 12, 2017"
2,3.,"""Shape of You""[25]",Ed Sheeran,5.29,"January 30, 2017"
3,4.,"""Johny Johny Yes Papa""[26]",LooLoo Kids,5.24,"October 8, 2016"
4,5.,"""See You Again""[27]",Wiz Khalifa,5.08,"April 6, 2015"
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.43,"January 31, 2012"
6,7.,"""Uptown Funk""[31]",Mark Ronson,4.16,"November 19, 2014"
7,8.,"""Gangnam Style""[32]",Psy,4.05,"July 15, 2012"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[34]",Miroshka TV,3.97,"February 27, 2018"
9,10.,"""Bath Song""[35]",Cocomelon – Nursery Rhymes,3.95,"May 2, 2018"
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,3.78,"March 6, 2014"
11,12.,"""Sugar""[37]",Maroon 5,3.45,"January 14, 2015"
12,13.,"""Sorry""[38]",Justin Bieber,3.43,"October 22, 2015"
13,14.,"""Roar""[39]",Katy Perry,3.34,"September 5, 2013"
14,15.,"""Dame Tu Cosita""[40]",El Chombo,3.28,"April 5, 2018"
15,16.,"""Counting Stars""[41]",OneRepublic,3.27,"May 31, 2013"
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.24,"October 7, 2014"
17,18.,"""Dark Horse""[43]",Katy Perry,3.05,"February 20, 2014"
18,19.,"""Faded""[44]",Alan Walker,3.05,"December 3, 2015"
19,20.,"""Shake It Off""[45]",Taylor Swift,3.05,"August 18, 2014"
20,21.,"""Lean On""[46]",Major Lazer Official,3.02,"March 22, 2015"
21,22.,"""Bailando""[47]",Enrique Iglesias,3.01,"April 11, 2014"
22,23.,"""Girls Like You""[48]",Maroon 5,3.01,"May 31, 2018"
23,24.,"""Let Her Go""[49]",Passenger,2.97,"July 25, 2012"
24,25.,"""Mi Gente""[50]",J Balvin,2.90,"June 29, 2017"
25,26.,"""Wheels on the Bus""[51]",Cocomelon – Nursery Rhymes,2.89,"May 24, 2018"
26,27.,"""Hello""[52]",Adele,2.83,"October 22, 2015"
27,28.,"""Perfect""[53]",Ed Sheeran,2.82,"November 9, 2017"
28,29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,2.80,"June 4, 2010"
29,30.,"""Axel F""[55]",Crazy Frog,2.77,"June 16, 2009"

In [131]:
#closing driver.
driver.close()

# TASK 2

In [132]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://www.bcci.tv/'
    #getting the driver
driver.get(URL)

In [133]:
#getting the url for international fixtures
intfix_url=driver.find_element_by_xpath('//a[@class="navigation__link navigation__link--in-drop-down"]').get_attribute('href')

In [134]:
#navigating to the page.
driver.get(intfix_url)

In [138]:
#this gets match title and place
Match=driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]')

In [139]:
len(Match)

6

In [140]:
Match[1].text.split("\n")

['1st Test', 'Trent Bridge, Nottingham']

In [141]:
series=driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__format"]')

In [142]:
series[0].text

'TEST'

In [143]:
time=driver.find_elements_by_xpath('//span[@class="fixture__time"]')

In [144]:
time[0].text

'15:30 IST'

In [145]:
time[1].text

'15:30 IST'

In [146]:
day=driver.find_elements_by_xpath('//span[@class="fixture__day"]')

In [147]:
date=driver.find_elements_by_xpath('//span[@class="fixture__date"]')

In [148]:
month=driver.find_elements_by_xpath('//span[@class="fixture__month"]')

In [149]:
fullDate=[]
Title=[]
Place=[]

In [150]:
for i in range(6):
    Match[i]=Match[i].text.split("\n")#Match contains info about title and place,separated by \n so splitting it based on \n
    
    Title.append(Match[i][0])#0th element of match contains title
    Place.append(Match[i][1])#1st element of match contains place 
    series[i]=series[i].text
    time[i]=time[i].text
    day[i]=day[i].text
    date[i]=date[i].text
    month[i]=month[i].text
    fullDate.append(day[i]+" "+date[i]+" "+month[i])

In [151]:
#saving lists as columns to the data frame.
Intnl_fixtrDF=pd.DataFrame({'Match Title':Title,
                            'Series':series,
                            'Place':Place,
                            'Time':time,
                            'Date':fullDate
    
})

In [152]:
#final data frame.
Intnl_fixtrDF

,Match Title,Series,Place,Time,Date
0,Final,TEST,"The Ageas Bowl, Southampton",15:30 IST,Friday 18 JUNE
1,1st Test,TEST,"Trent Bridge, Nottingham",15:30 IST,Wednesday 04 AUGUST
2,2nd Test,TEST,"Lord's, London",15:30 IST,Thursday 12 AUGUST
3,3rd Test,TEST,"Headingley, Leeds",15:30 IST,Wednesday 25 AUGUST
4,4th Test,TEST,"The Oval, London",15:30 IST,Thursday 02 SEPTEMBER
5,5th Test,TEST,"Old Trafford, Manchester",15:30 IST,Friday 10 SEPTEMBER

In [153]:
#closing driver.
driver.close()

# TASK 3

In [154]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://www.guru99.com/'
    #getting the driver
driver.get(URL)

There is a selenium icon on the page when clicking on it,it takes us to the selenium tutorial page.

In [155]:
#getting the driver for slenium icon
d=driver.find_element_by_xpath('//*[@id="g-above"]/div/div/div/div/div/div/div/div[2]/div/div[2]/span[8]/a')

In [156]:
#clicking the selenium icon on home page.this takes us to selenium tutorials.
d.click()

The selenium tuttorial page displays variety of tutorials.

Under Advanced web driver stuff,there is selenium exception handling in the last row.

getting the driver for exception handling page.

In [157]:
excep_page=driver.find_element_by_xpath('//*[@id="g-mainbar"]/div/div/div/div/div/div/div[2]/table[5]/tbody/tr[34]/td[1]/a')

In [158]:
excep_page.click()

Now the desired page will be loaded.

Extracting the required info.

In [159]:
name=[]
description=[]

In [160]:
for i in range(2,43):
    name.append(driver.find_element_by_xpath('//*[@id="g-mainbar"]/div[1]/div/div/div/div/div/div[2]/table/tbody/tr['+str(i)+']/td[1]').text)
    description.append(driver.find_element_by_xpath('//*[@id="g-mainbar"]/div[1]/div/div/div/div/div/div[2]/table/tbody/tr['+str(i)+']/td[2]').text)

In [161]:
name

['ElementNotVisibleException',
 'ElementNotSelectableException',
 'NoSuchElementException',
 'NoSuchFrameException',
 'NoAlertPresentException',
 'NoSuchWindowException',
 'StaleElementReferenceException',
 'SessionNotFoundException',
 'TimeoutException',
 'WebDriverException',
 'ConnectionClosedException',
 'ElementClickInterceptedException',
 'ElementNotInteractableException',
 'ErrorInResponseException',
 'ErrorHandler.UnknownServerException',
 'ImeActivationFailedException',
 'ImeNotAvailableException',
 'InsecureCertificateException',
 'InvalidArgumentException',
 'InvalidCookieDomainException',
 'InvalidCoordinatesException',
 'InvalidElementStateExceptio',
 'InvalidSessionIdException',
 'InvalidSwitchToTargetException',
 'JavascriptException',
 'JsonException',
 'NoSuchAttributeException',
 'MoveTargetOutOfBoundsException',
 'NoSuchContextException',
 'NoSuchCookieException',
 'NotFoundException',
 'RemoteDriverServerException',
 'ScreenshotException',
 'SessionNotCreatedException',
 'UnableToSetCookieException',
 'UnexpectedTagNameException',
 'UnhandledAlertException',
 'UnexpectedAlertPresentException',
 'UnknownMethodException',
 'UnreachableBrowserException',
 'UnsupportedCommandException']

In [162]:
description

['This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 'This Exception occurs if an element could not be found.',
 'This Exception occurs if the frame target to be switched to does not exist.',
 'This Exception occurs when you switch to no presented alert.',
 'This Exception occurs if the window target to be switch does not exist.',
 'This Selenium exception occurs happens when the web element is detached from the current DOM.',
 'The WebDriver is acting after you quit the browser.',
 "Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn't found in the specified time.",
 'This Exception takes place when the WebDriver is acting right after you close the browser.',
 'This type of Exception takes place when there is a disconnection in the driver.',
 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 'This happens while interacting with the Firefox extension or the remote driver server.',
 'Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 'This expectation will occur when IME engine activation has failed.',
 'It takes place when IME support is unavailable.',
 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 'It occurs when an argument does not belong to the expected type.',
 'This happens when you try to add a cookie under a different domain instead of current URL.',
 'This type of Exception matches an interacting operation that is not valid.',
 "It occurs when command can't be finished when the element is invalid.",
 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 'This occurs when the frame or window target to be switched does not exist.',
 'This issue occurs while executing JavaScript given by the user.',
 'It occurs when you afford to get the session when the session is not created.',
 'This kind of Exception occurs when the attribute of an element could not be found.',
 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 'ContextAware does mobile device testing.',
 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 'It is not possible to capture a screen.',
 'It happens when a new session could not be successfully created.',
 'This occurs if a driver is unable to set a cookie.',
 'Happens if a support class did not get a web element as expected.',
 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 'It occurs when there is the appearance of an unexpected alert.',
 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 "This occurs when remote WebDriver does n't send valid commands as expected."]

In [163]:
#appending the lists as column to the data frame.
Selenium_Exceptions=pd.DataFrame({'Exception Name':name,
                                  'Description':description
    
})

In [164]:
#final data frame.
Selenium_Exceptions

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

In [165]:
#closing driver.
driver.close()

# TASK 4

In [166]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='http://statisticstimes.com/'
    #getting the driver
driver.get(URL)

In [167]:
#clicking the world button it displays three options
driver.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/button').click()

In [168]:
#getting url of india statistics
Chose_Ind=driver.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/div/a[3]').get_attribute('href')

In [169]:
Chose_Ind

'http://statisticstimes.com/economy/india-statistics.php'

In [170]:
#navigating to the page.
driver.get(Chose_Ind)

In [171]:
chose_state=driver.find_elements_by_xpath('//a[@class="ec"]')

In [172]:

for i in range(len(chose_state)):
    if chose_state[i].text == "» GDP of Indian states" :
        stateurl=chose_state[i].get_attribute("href")
        
    else:
        pass

In [173]:
stateurl

'http://statisticstimes.com/economy/india/indian-states-gdp.php'

In [175]:
driver.get(stateurl)

In [176]:
rank=[]
state=[]
gsdp19_20=[]
gsdf18_19=[]
share18_19=[]
gdp=[]

In [177]:
for i in range(33):
    rank.append(driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i+1)+']/td[1]').text)
    state.append(driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i+1)+']/td[2]').text)
    gsdp19_20.append(driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i+1)+']/td[3]').text)
    gsdf18_19.append(driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i+1)+']/td[4]').text)
    share18_19.append(driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i+1)+']/td[5]').text)
    gdp.append(driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i+1)+']/td[6]').text)

In [178]:
stategdp_df=pd.DataFrame({'Rank':rank,
                          'Sate':state,
                          'GSDP 19-20':gsdp19_20,
                          'GSDP 18-19':gsdf18_19,
                          'Share(18-19)':share18_19,
                          'GDP':gdp
    
})

In [179]:
stategdp_df

   Rank                       Sate GSDP 19-20 GSDP 18-19 Share(18-19)      GDP
0     1                Maharashtra          -  2,632,792       13.88%  398.145
1     2                 Tamil Nadu  1,845,853  1,630,208        8.59%  246.529
2     3              Uttar Pradesh  1,687,818  1,584,764        8.35%  239.656
3     4                    Gujarat          -  1,502,899        7.92%  227.276
4     5                  Karnataka  1,631,977  1,493,127        7.87%  225.798
5     6                West Bengal  1,253,832  1,089,898        5.75%  164.820
6     7                  Rajasthan  1,020,989    942,586        4.97%  142.543
7     8             Andhra Pradesh    972,782    862,957        4.55%  130.501
8     9                  Telangana    969,604    861,031        4.54%  130.210
9    10             Madhya Pradesh    906,672    809,592        4.27%  122.431
10   11                     Kerala          -    781,653        4.12%  118.206
11   12                      Delhi    856,112    774,870        4.08%  117.180
12   13                    Haryana    831,610    734,163        3.87%  111.024
13   14                      Bihar    611,804    530,363        2.80%   80.204
14   15                     Punjab    574,760    526,376        2.77%   79.601
15   16                     Odisha    521,275    487,805        2.57%   73.768
16   17                      Assam          -    315,881        1.67%   47.769
17   18               Chhattisgarh    329,180    304,063        1.60%   45.982
18   19                  Jharkhand    328,598    297,204        1.57%   44.945
19   20                Uttarakhand          -    245,895        1.30%   37.186
20   21            Jammu & Kashmir          -    155,956        0.82%   23.584
21   22           Himachal Pradesh    165,472    153,845        0.81%   23.265
22   23                        Goa     80,449     73,170        0.39%   11.065
23   24                    Tripura     55,984     49,845        0.26%    7.538
24   25                 Chandigarh          -     42,114        0.22%    6.369
25   26                 Puducherry     38,253     34,433        0.18%    5.207
26   27                  Meghalaya     36,572     33,481        0.18%    5.063
27   28                     Sikkim     32,496     28,723        0.15%    4.344
28   29                    Manipur     31,790     27,870        0.15%    4.215
29   30                   Nagaland          -     27,283        0.14%    4.126
30   31          Arunachal Pradesh          -     24,603        0.13%    3.721
31   32                    Mizoram     26,503     22,287        0.12%    3.370
32   33  Andaman & Nicobar Islands          -          -            -        -

In [180]:
driver.close()

# TASK 5

In [181]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://github.com/'
    #getting the driver
driver.get(URL)

In [182]:
#getting the url for trending 
TrndPage=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a').get_attribute('href')

In [183]:
#getting the trending page.
driver.get(TrndPage)

In [184]:
urls=[]

In [185]:
#adding all the urls of trending profiles to the list named urls.
for i in range(25):
   
   urls.append(driver.find_element_by_xpath('//*[@id="js-pjax-container"]/div[3]/div/div[2]/article['+str(i+1)+']/h1/a').get_attribute('href'))

In [186]:
urls

['https://github.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard',
 'https://github.com/pallupz/covid-vaccine-booking',
 'https://github.com/goharbor/harbor',
 'https://github.com/public-apis/public-apis',
 'https://github.com/jwasham/coding-interview-university',
 'https://github.com/DIGITALCRIMINAL/OnlyFans',
 'https://github.com/facebookincubator/cinder',
 'https://github.com/vinta/awesome-python',
 'https://github.com/jlevy/the-art-of-command-line',
 'https://github.com/dogecoin/dogecoin',
 'https://github.com/phamdinhkhanh/vnquant',
 'https://github.com/audacity/audacity',
 'https://github.com/Uniswap/uniswap-v3-periphery',
 'https://github.com/swar/Swar-Chia-Plot-Manager',
 'https://github.com/flutter/flutter',
 'https://github.com/streamich/react-use',
 'https://github.com/dynamicwebpaige/thinking-in-data',
 'https://github.com/forem/forem',
 'https://github.com/Azure/counterfit',
 'https://github.com/Uniswap/uniswap-v3-core',
 'https://github.com/ionic-team/ionic-framework',
 'https://github.com/thedevdojo/wave',
 'https://github.com/devsuperior/sds3',
 'https://github.com/angular/angular-cli',
 'https://github.com/benawad/dogehouse']

In [187]:
#creating empty lists to add values later.
title=[]
desc=[]
contributors=[]
languages=[]

In [188]:
#looping through each url and extracting the required info.
for i in range(len(urls)):
    driver.get(urls[i])
    try:
        title.append(driver.find_element_by_xpath('//*[@id="js-repo-pjax-container"]/div[1]/div[1]/div/h1/strong/a').text)
    except NoSuchElementException:
        title.append('----')
    try:
        desc.append(driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div/p').text)
    except NoSuchElementException:
        desc.append('------')
    try:
        a=driver.find_elements_by_xpath('//a[@class="Link--primary no-underline "]')
        #the above xpath reteives multiple info like relases,packages,etc.
        for i in range(len(a)):
            elements=[]
            elements.append(a[i].text)
        #we need contributors,the contributors are usually present at last in the list.
        #After exiting the  for loop,the list named elements holds the last element from xpath which is mostly contributors if contributors are present.
        #In few cases where contibutors are not present,the list may contain null or the last element.
        #print("::",elements)
        
        #the below syntax saves contributors into chk_contribts. 
        chk_contribts = [string for string in elements if 'Contributors' in string]
       
        #if chk_contribts is not  null below stmt executes.
        if len(chk_contribts)!=0:
            contributors.append(chk_contribts)
        
        else:
            #if chk_contribts is null below stmt executes.
            contributors.append('No Contributors')
        
    except NoSuchElementException:
        contributors.append('----')
    try:
        l=[]
        q=driver.find_elements_by_xpath('//span[@class="color-text-primary text-bold mr-1"]')
        for j in range(len(q)):
                l.append(q[j].text)
        languages.append(l)
        
    except NoSuchElementException:
        languages.append('-----')

In [189]:
gitTrending_df=pd.DataFrame({'Repository Title':title,
                             'Repository Description':desc,
                             'Contributors count':contributors,
                             'Languages Used':languages
    
})

In [190]:
gitTrending_df

,Repository Title,Repository Description,Contributors count,Languages Used
0,Flutter-Responsive-Admin-Panel-or-Dashboard,Responsive Admin Panel or Dashboard using Flutter,No Contributors,"[Dart, Ruby, HTML, Swift, Other]"
1,covid-vaccine-booking,This very basic script can be used to automate...,[Contributors 7],[Python]
2,harbor,An open source trusted cloud native registry p...,[Contributors 214],"[Go, TypeScript, HTML, Python, RobotFramework,..."
3,public-apis,A collective list of free APIs,[Contributors 765],"[Python, Shell]"
4,coding-interview-university,A complete computer science study plan to beco...,[Contributors 196],[]
5,OnlyFans,Scrape all the media from an OnlyFans account ...,[Contributors 21],"[Python, Other]"
6,cinder,Instagram's performance oriented fork of CPython.,[Contributors 9],"[Python, C, C++, HTML, M4, Batchfile, Other]"
7,awesome-python,"A curated list of awesome Python frameworks, l...",[Contributors 391],"[Python, Makefile]"
8,the-art-of-command-line,"Master the command line, in one page",[Contributors 162],[]
9,dogecoin,very currency,[Contributors 201],"[C++, Python, C, M4, Makefile, HTML, Other]"
10,vnquant,VietNam Data Stock Market Price,No Contributors,"[HTML, Other]"
11,audacity,Audio Editor,[Contributors 126],"[C, C++, Python, Shell, Makefile, HTML, Other]"
12,uniswap-v3-periphery,🦄 🦄 🦄 Peripheral smart contracts for interacti...,[Contributors 8],"[TypeScript, Solidity]"
13,Swar-Chia-Plot-Manager,This is a Cross-Platform Plot Manager for Chia...,[Contributors 7],[Python]
14,flutter,Flutter makes it easy and fast to build beauti...,[Contributors 851],"[Dart, Objective-C, Java, Shell, C++, CMake, O..."
15,react-use,React Hooks — 👍,[Contributors 164],"[TypeScript, JavaScript]"
16,thinking-in-data,A VS Code extension pack to help users visuali...,No Contributors,[]
17,forem,For empowering community 🌱,[Contributors 578],"[Ruby, JavaScript, HTML, SCSS, Shell, VCL]"
18,counterfit,a CLI that provides a generic automation layer...,[Contributors 578],"[Python, Dockerfile]"
19,uniswap-v3-core,🦄 🦄 🦄 Core smart contracts of Uniswap v3,[Contributors 8],"[TypeScript, Solidity]"
20,ionic-framework,A powerful cross-platform UI toolkit for build...,[Contributors 407],"[TypeScript, HTML, SCSS, JavaScript, Vue, CSS,..."
21,wave,"Wave - The Software as a Service Starter Kit, ...",[Contributors 2],"[PHP, Blade, Shell]"
22,sds3,------,No Contributors,[]
23,angular-cli,CLI tool for Angular,[Contributors 531],"[TypeScript, Starlark, JavaScript, EJS, HTML, ..."
24,dogehouse,Taking voice conversations to the moon 🚀,[Contributors 388],"[TypeScript, Elixir, HTML, JavaScript, Java, O..."

In [191]:
#closing driver.
driver.close()

# TASK 6

In [192]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://www.billboard.com/'
    #getting the driver
driver.get(URL)

In [193]:
Hot100url=driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[2]/nav/ul/li[3]/a').get_attribute('href')

In [194]:
Hot100url

'https://www.billboard.com/charts/hot-100'

In [195]:
driver.get(Hot100url)

In [196]:
song=driver.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]')

In [197]:
artist=driver.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]')

In [198]:
lastwk=driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')

In [199]:
pkrnk=driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]')

In [200]:
wekonboard=driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')

In [201]:
for i in range(100):
    song[i]=song[i].text
    artist[i]=artist[i].text
    lastwk[i]=lastwk[i].text
    pkrnk[i]=pkrnk[i].text
    wekonboard[i]=wekonboard[i].text

In [202]:
song

['Save Your Tears',
 'Leave The Door Open',
 'Peaches',
 'Rapstar',
 'Levitating',
 'Kiss Me More',
 'Montero (Call Me By Your Name)',
 'Astronaut In The Ocean',
 'Up',
 'Drivers License',
 'Blinding Lights',
 'Deja Vu',
 'Beat Box',
 'Calling My Phone',
 'On Me',
 'Best Friend',
 'Heartbreak Anniversary',
 'Beautiful Mistakes',
 'What You Know Bout Love',
 'Mood',
 "My Ex's Best Friend",
 'Back In Blood',
 'Without You',
 'The Good Ones',
 'Go Crazy',
 'You Broke Me First.',
 '34+35',
 'Hell Of A View',
 'Forever After All',
 "What's Next",
 'Time Today',
 'Therefore I Am',
 'Dakiti',
 'Positions',
 'Shottas (Lala)',
 'Solid',
 'Track Star',
 'Ski',
 'Wants And Needs',
 "You're Mines Still",
 "We're Good",
 'Heat Waves',
 'Made For You',
 'Good Days',
 'For The Night',
 "Breaking Up Was Easy In The 90's",
 'No More Parties',
 'Goosebumps',
 'Telepatia',
 'Tombstone',
 'Streets',
 'Go!',
 'Hard For The Next',
 'If Pain Was A Person',
 "What's Your Country Song",
 'Just The Way',
 'Hold On',
 'Settling Down',
 'Wockesha',
 'Botella Tras Botella',
 'Willow',
 'Damage',
 'Street Runner',
 'Come Through',
 'Somebody Like That',
 'pov',
 'Lil Bit',
 'Gone',
 'Nobody',
 'Famous Friends',
 'Quicksand',
 'Lady',
 'The Business',
 'La Noche de Anoche',
 'One Too Many',
 'Richer',
 'Almost Maybes',
 'Follow You',
 'Glad You Exist',
 'Free Promo',
 'Pick Up Your Feelings',
 'Just Say Det',
 'Big Gangsta',
 'Down To One',
 'Headshot',
 'Hellcats & Trackhawks',
 'Anyone',
 'My Head And My Heart',
 'How They Remember You',
 'Arcade',
 "Drunk (And I Don't Wanna Go Home)",
 'Masterpiece',
 'Long Live',
 'Chasing After You',
 'Drankin N Smokin',
 '4 Da Gang',
 'Blame It On You',
 'Wasted On You',
 'Way Less Sad',
 'Clear Da Air']

In [203]:
billbord_hot100=pd.DataFrame({'Song Name':song,
                              'Artist Name':artist,
                              'Last week Rank':lastwk,
                              'Peak Rank':pkrnk,
                              'weeks on board':wekonboard
                             })

In [204]:
billbord_hot100

,Song Name,Artist Name,Last week Rank,Peak Rank,weeks on board
0,Save Your Tears,The Weeknd & Ariana Grande,6,1,20
1,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),2,1,8
2,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,3,1,6
3,Rapstar,Polo G,1,1,3
4,Levitating,Dua Lipa Featuring DaBaby,5,5,30
...,...,...,...,...,...
95,4 Da Gang,42 Dugg & Roddy Ricch,100,67,4
96,Blame It On You,Jason Aldean,-,97,1
97,Wasted On You,Morgan Wallen,92,9,16
98,Way Less Sad,AJR,-,99,1
99,Clear Da Air,Moneybagg Yo,-,100,1

In [205]:
#closing driver.
driver.close()

# TASK 7

In [206]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://www.naukri.com/'
    #getting the driver
driver.get(URL)

In [207]:
rctr_url=driver.find_element_by_xpath('//a[@title="Search Recruiters"]').get_attribute('href')

In [208]:
rctr_url

'https://www.naukri.com/recruiters'

In [209]:
driver.get(rctr_url)

In [210]:
inputtext=driver.find_element_by_xpath('//input[@class="sugInp"]')

In [211]:
inputtext.send_keys('Data science')

In [212]:
driver.find_element_by_xpath('//button[@id="qsbFormBtn"]').click()

In [213]:
#getting urls of all the profiles.
urls=[]
for i in range(25):
    for j in range(2):
        q=driver.find_element_by_xpath('//*[@id="tabP-1"]/div['+str(i+1)+']/div['+str(j+1)+']/div[1]/div[1]/div/a')
        urls.append(q.get_attribute('href'))

In [214]:
urls

['https://www.naukri.com/recruiters/aakashharit-1986742?xid=162037201896506400&xp=1',
 'https://www.naukri.com/recruiters/shravankumargaddam-353487?xid=162037201896506400&xp=2',
 'https://www.naukri.com/recruiters/Xenonstack?xid=162037201896506400&xp=3',
 'https://www.naukri.com/recruiters/anikagrawal-3647208?xid=162037201896506400&xp=4',
 'https://www.naukri.com/recruiters/marsiantech?xid=162037201896506400&xp=5',
 'https://www.naukri.com/recruiters/LXP-DATASCIENCE?xid=162037201896506400&xp=6',
 'https://www.naukri.com/recruiters/abhishekyadav-3450244?xid=162037201896506400&xp=7',
 'https://www.naukri.com/recruiters/menakav-3213816?xid=162037201896506400&xp=8',
 'https://www.naukri.com/recruiters/techvantage?xid=162037201896506400&xp=9',
 'https://www.naukri.com/recruiters/asiflucknowi-4331110?xid=162037201896506400&xp=10',
 'https://www.naukri.com/recruiters/instafinancials-humanresource?xid=162037201896506400&xp=11',
 'https://www.naukri.com/recruiters/kalpana-2078894?xid=162037201896506400&xp=12',
 'https://www.naukri.com/recruiters/mubarak-2905498?xid=162037201896506400&xp=13',
 'https://www.naukri.com/recruiters/quantmagnum?xid=162037201896506400&xp=14',
 'https://www.naukri.com/recruiters/ruchidhote?xid=162037201896506400&xp=15',
 'https://www.naukri.com/recruiters/maheshbabuchanna-1803238?xid=162037201896506400&xp=16',
 'https://www.naukri.com/recruiters/kapildevang-3169734?xid=162037201896506400&xp=17',
 'https://www.naukri.com/recruiters/priyakhare-4894796?xid=162037201896506400&xp=18',
 'https://www.naukri.com/recruiters/manishayadav-4463916?xid=162037201896506400&xp=19',
 'https://www.naukri.com/recruiters/riyarajesh-4375878?xid=162037201896506400&xp=20',
 'https://www.naukri.com/recruiters/rashmibhattacharjee-3921774?xid=162037201896506400&xp=21',
 'https://www.naukri.com/recruiters/faizankareem-3685102?xid=162037201896506400&xp=22',
 'https://www.naukri.com/recruiters/rithikadadwal-3517898?xid=162037201896506400&xp=23',
 'https://www.naukri.com/recruiters/azaharshaikh-companyrecruiter?xid=162037201896506400&xp=24',
 'https://www.naukri.com/recruiters/ankitshah-21129?xid=162037201896506400&xp=25',
 'https://www.naukri.com/recruiters/shaunrao-3020604?xid=162037201896506400&xp=26',
 'https://www.naukri.com/recruiters/manas-3159036?xid=162037201896506400&xp=27',
 'https://www.naukri.com/recruiters/kumar-3378892?xid=162037201896506400&xp=28',
 'https://www.naukri.com/recruiters/sunilvedula-3392046?xid=162037201896506400&xp=29',
 'https://www.naukri.com/recruiters/rajatkumar-3295096?xid=162037201896506400&xp=30',
 'https://www.naukri.com/recruiters/dhruvdevdubey?xid=162037201896506400&xp=31',
 'https://www.naukri.com/recruiters/jayanthn-3081850?xid=162037201896506400&xp=32',
 'https://www.naukri.com/recruiters/sreedhar-3824102?xid=162037201896506400&xp=33',
 'https://www.naukri.com/recruiters/prateekkumar-4410750?xid=162037201896506400&xp=34',
 'https://www.naukri.com/recruiters/amitsharma-4238940?xid=162037201896506400&xp=35',
 'https://www.naukri.com/recruiters/deepali002g?xid=162037201896506400&xp=36',
 'https://www.naukri.com/recruiters/shashikantchaudhary-4164854?xid=162037201896506400&xp=37',
 'https://www.naukri.com/recruiters/brad-4068508?xid=162037201896506400&xp=38',
 'https://www.naukri.com/recruiters/rutujapawar?xid=162037201896506400&xp=39',
 'https://www.naukri.com/recruiters/madhusudhansridhar-2705338?xid=162037201896506400&xp=40',
 'https://www.naukri.com/recruiters/ankitsinha-3398798?xid=162037201896506400&xp=41',
 'https://www.naukri.com/recruiters/gauravchouhan?xid=162037201896506400&xp=42',
 'https://www.naukri.com/recruiters/impel?xid=162037201896506400&xp=43',
 'https://www.naukri.com/recruiters/ashwini-3434922?xid=162037201896506400&xp=44',
 'https://www.naukri.com/recruiters/balajikolli-2870676?xid=162037201896506400&xp=45',
 'https://www.naukri.com/recruiters/rajaninagaraj-3387578?xid=162037201896506400&xp=46',
 'https://www.naukri.com/recruiters/rohitkumar-3277680?xid=162037201896506400&xp=47',
 'https://www.naukri.com/recruiters/amirchowdhury-2925314?xid=162037201896506400&xp=48',
 'https://www.naukri.com/recruiters/shailjamishra-hrmanager-noida?xid=162037201896506400&xp=49',
 'https://www.naukri.com/recruiters/sunnysharma-mumbai?xid=162037201896506400&xp=50']

In [215]:
#lists for adding info
names=[]
location=[]
skills=[]
company=[]
job=[]

In [216]:
#iterating through urls of each recruiter and extracting the info.
for i in range(len(urls)):
    driver.get(urls[i])
    try:
        names.append(driver.find_element_by_xpath('//h1[@class="fl ellipsis wLimit hd"]').text)
    except NoSuchElementException:
        names.append('------')
    try:
        location.append(driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[1]/div[2]/div[5]').text)
    except NoSuchElementException:
        location.append('-------')
    try:
        skills.append(driver.find_element_by_xpath('//*[@id="skillInfo"]/p[1]').text)
    except NoSuchElementException:
        skills.append('---------')
    try:
        company.append(driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[1]/div[2]/div[4]').text)
    except NoSuchElementException:
        company.append('---------')
    try:
        job.append(driver.find_element_by_xpath('//div[@class="ellipsis"]').text)
    except NoSuchElementException:
        job.append('-----------')

In [217]:
Ds_recruiters_df=pd.DataFrame({'Name':names,
                               'Designation':job,
                               'Company':company,
                               'Skills hiring for':skills,
                               'Location':location
    
})

In [218]:
Ds_recruiters_df

,Name,Designation,Company,Skills hiring for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer , Internet Marketing Pro...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net , Java , Data Science , Linux Administrat...",Hyderabad / Secunderabad
2,Talent Acquisition Executive,Recruitment Professional,XenonStack,"Web Designing , html5 , Angular.js , seo , had...",Chandigarh
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,", Mean Stack , javascript , angularjs , mongod...",Ahmedabad
4,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Mid Level, Junior Level",Pune
5,subhas patel,Founder & CEO,LibraryXProject,"Hadoop , Spark , Digital Strategy , Data Archi...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and APAC,Recruitment - Lead Consultant,Apidel Technologies Division of Transpower,"Analytics , Business Intelligence , Business A...",Vadodara / Baroda
7,Institute for Financial Management and Research,Programme Manager,IFMR,Analytics & Business Intelligence,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning , algorithms , Go Getter , Co...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,---------,Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Junior Level, Mid Level",Bengaluru / Bangalore
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa , Ui , ux , Java Developer , Java Architect...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,---------,Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,---------,Mumbai
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,IT Skills,Nagpur
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Junior Level, Mid Level",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data , Hadoop , Data Analytics , Data Science",Bhopal
17,Priya Khare,Senior Manager,Independent Consultant,---------,Bengaluru / Bangalore
18,Manisha Yadav,HR Executive,Easi Tax,Mid Level,Navi Mumbai
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,IT-Software/Software Services,Cochin
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE LIMITED,"Mid Level, Top Mangement Level",Delhi
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics , Data Science , Machine Learni...",Hyderabad / Secunderabad
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Junior Level, Mid Level",Pune
23,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Mid Level, High Level",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"High Level, Mid Level",Pune
25,Shaun Rao,Manager - Human Resources,Exela Technologies,"Java , Net , Angularjs , Hr , Infrastructure ,...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private Limited,"High Level, Top Mangement Level",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science , Hadoop , Rpas , Devops , Python...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing , Machine Learning , Neural ...",Others
29,Rajat Kumar,Founder & CEO,R.S Consultancy & Services,"Web Technologies , Project Management , Softwa...",Delhi
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"S. Finance Manager , Freshers , Experience , S...",Bengaluru / Bangalore
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics , Managed Services , Team Leading",Mysoru / Mysore
32,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,---------,Hyderabad / Secunderabad
33,Prateek Kumar,Head,Trisect,Junior Level,Noida
34,Amit Sharma,Consultant,ASCO consulting,---------,New Delhi
35,Kanan,senior technology instructor,NY INST,"Mid Level, Junior Level",Chennai
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research & Consulting Co. India,---------,Aligarh
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Junior Level, High Level",Salt Lake City
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Python , Php , Qa Automation , Ui , Wordpre",Pune
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,---------,Bengaluru / Bangalore
40,Ankit Sinha,Head-Analytics,Suntech Global,---------,Mumbai
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Top Mangement Level, Junior Level",Indore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science , Node.js , Angularjs",Bengaluru / Bangalore
43,Ashwini,"Director, Global Delivery",MRP Advisers,---------,MYSORE
44,Balaji Kolli,Co-Founder,Saras Solutions India Pvt Ltd,---------,Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"java , hadoop , r , Machine Learning , spark ,...",Bengaluru / Bangalore
46,ROHIT Kumar,Architect,LNT Private Limited,"Mid Level, High Level",Mumbai
47,Amir Chowdhury,Managing Partner,Granular.ai,---------,
48,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,---------,Noida
49,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals , Engineering , Technic...",Mumbai

In [219]:
#closing driver.
driver.close()

# TASK 8

In [220]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
    #getting the driver
driver.get(URL)

In [221]:
book=[]
author=[]
volumes=[]
publisher=[]
genre=[]

In [222]:
for i in range(100):
        
        book.append(driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-1"]').text)
        author.append(driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-2"]').text)
        volumes.append(driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-3"]').text)
        publisher.append(driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-4"]').text)
        genre.append(driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-5"]').text)

In [223]:
HighSellingNovels_df=pd.DataFrame({'Book Name':book,
                                   'Author Name':author,
                                   'Volumes Sold':volumes,
                                   'Publisher':publisher,
                                   'Genre':genre
    
})

In [224]:
HighSellingNovels_df

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [225]:
#closing driver.
driver.close()

# TASK  9

In [226]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://www.imdb.com/list/ls095964455/'
#getting the driver
driver.get(URL)

In [227]:
name=[]
year=[]
genre=[]
rating=[]
votes=[]
runtime=[]

In [228]:
for i in range(100):
    name.append(driver.find_element_by_xpath('//*[@id="main"]/div/div[3]/div[3]/div['+str(i+1)+']/div[2]/h3/a').text)
    year.append(driver.find_element_by_xpath('//*[@id="main"]/div/div[3]/div[3]/div['+str(i+1)+']/div[2]/h3/span[2]').text)
    genre.append(driver.find_element_by_xpath('//*[@id="main"]/div/div[3]/div[3]/div['+str(i+1)+']/div[2]/p[1]/span[5]').text)
    rating.append(driver.find_element_by_xpath('//*[@id="main"]/div/div[3]/div[3]/div['+str(i+1)+']/div[2]/div[1]/div[1]/span[2]').text)
    votes.append(driver.find_element_by_xpath('//*[@id="main"]/div/div[3]/div[3]/div['+str(i+1)+']/div[2]/p[4]').text)
    runtime.append(driver.find_element_by_xpath('//*[@id="main"]/div/div[3]/div[3]/div['+str(i+1)+']/div[2]/p[1]/span[3]').text)

In [229]:
MostWatchdSeries=pd.DataFrame({ 'Name':name,
                               'Year Span':year,
                               'Genre':genre,
                               'Run Time':runtime,
                               'Ratings':rating,
                               'Votes':votes
    
})

In [230]:
MostWatchdSeries

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"Votes: 1,803,687"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"Votes: 848,571"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"Votes: 868,291"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"Votes: 260,369"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"Votes: 221,375"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"Votes: 44,238"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"Votes: 54,696"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"Votes: 165,613"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.2,"Votes: 34,601"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"Votes: 188,373"

In [231]:
#closing driver.
driver.close()

# TASK 10

In [238]:
#creating driver object
driver = webdriver.Chrome(r"C:/chromedriver.exe")
URL='https://archive.ics.uci.edu/'
#implicitly waiting 10 seconds to load the page.
driver.set_page_load_timeout(10)
#getting the driver
driver.get(URL)

In [239]:
ShowDatasets_url=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a').get_attribute('href')

In [240]:
ShowDatasets_url

'https://archive.ics.uci.edu/ml/datasets.php'

In [241]:
driver.get(ShowDatasets_url)

In [242]:
Name=[]
dtypes=[]
deftask=[]
attypes=[]
instncs=[]
attbts=[]
year=[]

In [243]:
for i in range(1,586):
    Name.append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i+1)+']/td[1]/table/tbody/tr/td[2]/p/b/a').text)
    dtypes.append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i+1)+']/td[2]/p').text)
    deftask.append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i+1)+']/td[3]/p').text)
    attypes.append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i+1)+']/td[4]/p').text)
    instncs.append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i+1)+']/td[5]/p').text)
    attbts.append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i+1)+']/td[6]/p').text)
    year.append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i+1)+']/td[7]/p').text)

In [244]:
uci_df=pd.DataFrame({ 'Data set Name':Name,
                     'Data Type':dtypes,
                     'Task':deftask,
                     'Attribute type':attypes,
                     'No.ofInstances':instncs,
                     'No.of Attributes':attbts,
                     'Year':year
    
})

In [245]:
uci_df

,Data set Name,Data Type,Task,Attribute type,No.ofInstances,No.of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
580,Wisesight Sentiment Corpus,"Multivariate, Text",Classification,,26737,4,2020
581,AI4I 2020 Predictive Maintenance Dataset,"Multivariate, Time-Series","Classification, Regression, Causal-Discovery",Real,10000,14,2020
582,Dry Bean Dataset,Multivariate,Classification,"Integer, Real",13611,17,2020
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020

In [246]:
#closing driver.
driver.close()